name: CI

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --verbose

  dockerize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: iwa
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/iwa/devops-back:latest

  notification:
    runs-on: ubuntu-latest
    needs: [build, dockerize]

    steps:
    - name: Trigger webhook
      uses: jasongitmail/fast-webhook@v1.1.4
      with:
        url: ${{ secrets.TRIGGER_WEBHOOK }}
